//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://myemulators2/v1", ClrNamespace="myemulators2.v1")]

namespace myemulators2.v1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameDetails", Namespace="http://myemulators2/v1")]
    public partial class GameDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private string FilenameField;
        
        private string GenreField;
        
        private string GradeField;
        
        private string HashField;
        
        private string ImageBackField;
        
        private string ImageFanartField;
        
        private string ImageFrontField;
        
        private string ImageIngameField;
        
        private string ImageTitleScreenField;
        
        private string ManualField;
        
        private string TitleField;
        
        private string YearField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename
        {
            get
            {
                return this.FilenameField;
            }
            set
            {
                this.FilenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre
        {
            get
            {
                return this.GenreField;
            }
            set
            {
                this.GenreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade
        {
            get
            {
                return this.GradeField;
            }
            set
            {
                this.GradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash
        {
            get
            {
                return this.HashField;
            }
            set
            {
                this.HashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageBack
        {
            get
            {
                return this.ImageBackField;
            }
            set
            {
                this.ImageBackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageFanart
        {
            get
            {
                return this.ImageFanartField;
            }
            set
            {
                this.ImageFanartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageFront
        {
            get
            {
                return this.ImageFrontField;
            }
            set
            {
                this.ImageFrontField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageIngame
        {
            get
            {
                return this.ImageIngameField;
            }
            set
            {
                this.ImageIngameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageTitleScreen
        {
            get
            {
                return this.ImageTitleScreenField;
            }
            set
            {
                this.ImageTitleScreenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manual
        {
            get
            {
                return this.ManualField;
            }
            set
            {
                this.ManualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://myemulators/Service/v1", ConfigurationName="CommunityServerWCFService")]
public interface CommunityServerWCFService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://myemulators/Service/v1/CommunityServerWCFService/SubmitGameDetails", ReplyAction="http://myemulators/Service/v1/CommunityServerWCFService/SubmitGameDetailsResponse" +
        "")]
    int SubmitGameDetails(myemulators2.v1.GameDetails game);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://myemulators/Service/v1/CommunityServerWCFService/RequestGameDetials", ReplyAction="http://myemulators/Service/v1/CommunityServerWCFService/RequestGameDetialsRespons" +
        "e")]
    myemulators2.v1.GameDetails RequestGameDetials(myemulators2.v1.GameDetails gameDetails);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface CommunityServerWCFServiceChannel : CommunityServerWCFService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CommunityServerWCFServiceClient : System.ServiceModel.ClientBase<CommunityServerWCFService>, CommunityServerWCFService
{
    
    public CommunityServerWCFServiceClient()
    {
    }
    
    public CommunityServerWCFServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CommunityServerWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CommunityServerWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CommunityServerWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int SubmitGameDetails(myemulators2.v1.GameDetails game)
    {
        return base.Channel.SubmitGameDetails(game);
    }
    
    public myemulators2.v1.GameDetails RequestGameDetials(myemulators2.v1.GameDetails gameDetails)
    {
        return base.Channel.RequestGameDetials(gameDetails);
    }
}
